
import Cabecalho from "@/components/Cabecalho/page.jsx"
import Rodape from "@/components/Rodape/page"
import { Inter } from 'next/font/google'
import './globals.css'

export const metadata = {
  title: 'Lojinha 1TDSR',
  description: 'Generated by augs e compania',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
    <body>
      <Cabecalho/>
       {children}
      <Rodape/>
    </body>
  </html>
  )
}
