import { Inter } from 'next/font/google'
import './globals.css'

import Cabecalho from "@/components/Cabecalho/page.jsx"
import Rodape from "@/components/Rodape/page"


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
    <body>
      <Cabecalho/>
       {children}
      <Rodape/>
    </body>
  </html>
  )
}
